### ISSUE TITLE
Comment 모델 관련 Lombok @Builder 옵션 빌드 문제

### ISSUE THREAD

**Issue by Kim-Changgyu** [prgrms-web-devcourse/Team-5YES-WuMo-BE#7]
### 📝 내용 설명
- develop 브랜치에서 Pull 받아 작업하던 중 다음과 같은 컴파일 에러가 발생했습니다.
```
error: builder() in PrivateRouteComment cannot hide builder() in Comment
	@Builder
	^
  return type PrivateRouteCommentBuilder is not compatible with CommentBuilder
```
- Comment를 상속하는 엔티티 모두 해당 오류가 발생함으로 조치가 필요할 것 같습니다.

**Comment by boompatron** [comment]
해당 문제는 상속관계에 얽힌 클래스의 생성자를 모두 Builder로 생성하려해서 생긴 문제입니다
Comment 의 모든 인자를 가진 생성자를 작성하였고, 이를 상속하는 LocationComment, PartyRouteComment가 각각 생성자에서 super를 호출해서 생긴 문제입니다.
여러 가지 해결 방법이 존재하지만, 가장 현실적인 방안으로 Comment 클래스의 Builder 어노테이션을 제거하였습니다.
해당 버그는 다음 커밋에서 수정했습니다
